project:
  type: website
  output-dir: docs

website:
  title: "A blog built with Quarto"
  site-url: https://jane-bunny.github.io/data-blog/ # you must change this appropriately for RSS feeds to work properly
  image: images/tool-stack.png
  open-graph: 
    title: "Jane's Data Blog"
    description: "A blog built with Quarto"
    image: images/tool-stack.png
  navbar:
    left:
      - text: "Data Blog"
        href: index.qmd
        icon: house
      - text: "Side Projects"
        href: side-project.qmd
        icon: joystick
    right:
      - text: "<i class='fa-solid fa-qrcode'></i> About <em>Me</em>"
        href: about.qmd
      - icon: github
        href: https://github.com/Jane-bunny
      - icon: linkedin
        href: https://www.linkedin.com/in/janezhang-techlearner
  page-footer: 
    foreground: rebellion
    left: "Â© 2025 Jane Zhang"
    right: "Built with <a href='https://quarto.org'>Quarto</a>"

format:
  html:
    theme:
      light:
        - flatly
        - brand.yml
        - custom.scss
      dark:
        - darkly
        - brand.yml
        - custom.scss
    css: styles.css
    include-in-header:
      - text: <script src="https://kit.fontawesome.com/c93529a43e.js" crossorigin="anonymous"></script>
